import { afterEach, expect, it, vi } from 'vitest';
import { act, cleanup, renderHook, waitFor } from '@testing-library/react';
import { taskFixture } from '@/lib/delegation.test-fixtures';
import type { LocalTask } from '@/lib/delegation';
import { readFileSync } from 'node:fs';
const native = vi.hoisted(() => ({ invoke: vi.fn(), listen: vi.fn() }));
vi.mock('@tauri-apps/api/core', () => ({ invoke: native.invoke }));
vi.mock('@tauri-apps/api/event', () => ({ listen: native.listen }));
afterEach(() => { cleanup(); vi.clearAllMocks(); });

it.skipIf(!process.env.CODEMUX_DELEGATION_CONTRACT_CAPTURE)('replays actual native command DTOs and invalidations through the production renderer store without feedback', async () => {
  const receipt=JSON.parse(readFileSync(process.env.CODEMUX_DELEGATION_CONTRACT_CAPTURE!,'utf8'));
  const store=await import('./delegation-store');
  let invalidate!:(event:{payload:{parent_thread_id:string}})=>void;
  native.listen.mockImplementation((event,callback)=>{expect(event).toBe('delegation-changed');invalidate=callback;return Promise.resolve(vi.fn());});
  let mutated=false;
  native.invoke.mockImplementation((cmd,args)=>{
    expect(cmd).toBe('delegation_list'); expect(args).toEqual({paneId:receipt.pane});
    const events=mutated?receipt.after_events:receipt.idle_events;
    if(native.invoke.mock.calls.length<10) for(const payload of events) invalidate({payload});
    return Promise.resolve(mutated?receipt.after_list:receipt.idle_list);
  });
  const hook=renderHook(()=>store.useDelegationTasks(receipt.pane,receipt.thread));
  await waitFor(()=>expect(hook.result.current.loading).toBe(false));
  expect(native.invoke).toHaveBeenCalledTimes(1);
  expect(hook.result.current.tasks[0].cancel_requested).toBe(false);
  await act(async()=>{mutated=true;for(const payload of receipt.mutation_events)invalidate({payload});});
  await waitFor(()=>expect(hook.result.current.tasks[0].cancel_requested).toBe(true));
  expect(native.invoke).toHaveBeenCalledTimes(2);
});

it('shares one invalidation/list path per pane and drops late results after thread changes', async () => {
  const modules = import.meta.glob('./delegation-store.ts');
  expect(modules['./delegation-store.ts'], 'shared delegation store must exist').toBeTypeOf('function');
  const store = await modules['./delegation-store.ts']() as typeof import('./delegation-store');
  let invalidate!: (event: { payload: { parent_thread_id: string } }) => void;
  const unlisten = vi.fn();
  native.listen.mockImplementation((_event, cb) => { invalidate = cb; return Promise.resolve(unlisten); });
  let resolveOld!: (tasks: LocalTask[]) => void;
  native.invoke.mockImplementation(() => new Promise<LocalTask[]>(resolve => { resolveOld = resolve; }));
  const one = renderHook(({ thread }) => store.useDelegationTasks('pane', thread), { initialProps: { thread: 'thread-1' } });
  const two = renderHook(() => store.useDelegationTasks('pane', 'thread-1'));
  await waitFor(() => expect(native.invoke).toHaveBeenCalledTimes(1));
  expect(native.listen).toHaveBeenCalledTimes(1);
  two.unmount();
  expect(unlisten).not.toHaveBeenCalled();
  native.invoke.mockResolvedValue([taskFixture({ id: 'new', parent_thread_id: 'thread-2' }), taskFixture()]);
  one.rerender({ thread: 'thread-2' });
  await waitFor(() => expect(one.result.current.tasks.map(task => task.id)).toEqual(['new']));
  await act(async () => { resolveOld([taskFixture()]); });
  expect(one.result.current.tasks.map(task => task.id)).toEqual(['new']);
  expect(unlisten).toHaveBeenCalledTimes(1);
  native.invoke.mockResolvedValue([taskFixture({ id: 'new', parent_thread_id: 'thread-2', status: 'completed' })]);
  await act(async () => { invalidate({ payload: { parent_thread_id: 'thread-1' } }); });
  expect(native.invoke).toHaveBeenCalledTimes(2);
  await act(async () => { invalidate({ payload: { parent_thread_id: 'thread-2' } }); });
  await waitFor(() => expect(one.result.current.tasks[0].status).toBe('completed'));
  expect(Object.isFrozen(one.result.current.tasks)).toBe(true);
  expect(Object.isFrozen(one.result.current.tasks[0])).toBe(true);
});

it('does not let an older list erase a confirmed launch inserted during readback', async () => {
  const store = await import('./delegation-store');
  native.listen.mockResolvedValue(vi.fn());
  let resolveList!: (tasks: LocalTask[]) => void;
  native.invoke.mockImplementationOnce(() => new Promise<LocalTask[]>(resolve => { resolveList = resolve; })).mockResolvedValue([taskFixture()]);
  const hook = renderHook(() => store.useDelegationTasks('launch-pane', 'thread-1'));
  await waitFor(() => expect(native.invoke).toHaveBeenCalledTimes(1));
  act(() => store.upsertDelegationTask('launch-pane', 'thread-1', taskFixture()));
  expect(hook.result.current.tasks).toHaveLength(1);
  const lengths: number[] = [];
  // A hook observer records committed snapshots, not mocked list contents.
  const observer = renderHook(() => { const state = store.useDelegationTasks('launch-pane', 'thread-1'); lengths.push(state.tasks.length); });
  await act(async () => { resolveList([]); });
  await waitFor(() => expect(native.invoke).toHaveBeenCalledTimes(2));
  expect(lengths).not.toContain(0);
  observer.unmount();
});

it('FEUI-3 retains immutable cloned responses only in the actual bounded pane/thread owner', async()=>{
 const store=await import('./delegation-store');native.listen.mockResolvedValue(vi.fn());native.invoke.mockResolvedValue([taskFixture()]);
 const hook=renderHook(({thread})=>store.useDelegationTasks('response-pane',thread),{initialProps:{thread:'thread-1'}});
 await waitFor(()=>expect(hook.result.current.loading).toBe(false));
 const request={request_id:'request',request_kind:'user-input',payload:{questions:[{question:'Exact?'}]}};
 const decision={decision:'allow' as const,updated_input:{...request.payload,answers:{'Exact?':'Original'}}};
 store.retainDelegationResponse('response-pane','thread-1','task-1',request,decision);
 decision.updated_input.answers['Exact?']='Changed outside cache';
 expect(store.retainedDelegationResponse('response-pane','thread-1','task-1','request')?.decision).toMatchObject({updated_input:{answers:{'Exact?':'Original'}}});
 expect(Object.isFrozen(store.retainedDelegationResponse('response-pane','thread-1','task-1','request')?.decision)).toBe(true);
 expect(store.retainedDelegationResponse('response-pane','foreign','task-1','request')).toBeUndefined();
 expect(store.retainedDelegationResponse('response-pane','thread-1','task-2','request')).toBeUndefined();
 expect(()=>store.retainDelegationResponse('response-pane','thread-1','task-1',{...request,payload:{changed:true}},decision)).toThrow(/payload changed/);
 for(let i=1;i<256;i++) store.retainDelegationResponse('response-pane','thread-1','task-1',{...request,request_id:`bounded-${i}`},{decision:'deny',message:'Same'});
 expect(()=>store.retainDelegationResponse('response-pane','thread-1','task-1',{...request,request_id:'overflow'},decision)).toThrow(/capacity/);
 hook.rerender({thread:'thread-2'});
 expect(store.retainedDelegationResponse('response-pane','thread-1','task-1','request')).toBeUndefined();
 hook.unmount();expect(store.isDelegationPaneOwner('response-pane','thread-2')).toBe(false);
});
it('consent boundary belongs to the actual owner, settles once and strands every pending read',async()=>{
 const store=await import('./delegation-store');native.listen.mockResolvedValue(vi.fn());native.invoke.mockResolvedValue([taskFixture()]);
 const hook=renderHook(({thread})=>store.useDelegationTasks('phase-pane',thread),{initialProps:{thread:'thread-1'}});
 await waitFor(()=>expect(hook.result.current.loading).toBe(false));
 const before=store.delegationResponseReadBoundary('phase-pane','thread-1','task-1');
 expect(store.qualifiesDelegationResponseRead('phase-pane','thread-1','task-1',before)).toBe(true);
 let settle!:()=>void;act(()=>{settle=store.beginDelegationResponse('phase-pane','thread-1','task-1');});
 const during=store.delegationResponseReadBoundary('phase-pane','thread-1','task-1');
 expect(store.qualifiesDelegationResponseRead('phase-pane','thread-1','task-1',before)).toBe(false);
 expect(store.qualifiesDelegationResponseRead('phase-pane','thread-1','task-1',during)).toBe(false);
 expect(()=>store.beginDelegationResponse('phase-pane','thread-1','task-1')).toThrow(/still pending/);
 act(()=>settle());const after=store.delegationResponseReadBoundary('phase-pane','thread-1','task-1');
 expect(store.qualifiesDelegationResponseRead('phase-pane','thread-1','task-1',during)).toBe(false);
 expect(store.qualifiesDelegationResponseRead('phase-pane','thread-1','task-1',after)).toBe(true);
 act(()=>settle());expect(store.qualifiesDelegationResponseRead('phase-pane','thread-1','task-1',after)).toBe(true);
 act(()=>{settle=store.beginDelegationResponse('phase-pane','thread-1','task-1');});
 hook.rerender({thread:'thread-2'});const replacement=store.delegationResponseReadBoundary('phase-pane','thread-2','task-1');
 act(()=>settle());expect(store.qualifiesDelegationResponseRead('phase-pane','thread-2','task-1',replacement)).toBe(true);
 expect(store.qualifiesDelegationResponseRead('phase-pane','thread-2','task-1',after)).toBe(false);
 hook.unmount();expect(store.qualifiesDelegationResponseRead('phase-pane','thread-2','task-1',replacement)).toBe(false);
});
it('keeps subscription failure distinct from successful refresh and disposes a late listener', async () => {
  const store = await import('./delegation-store');
  native.listen.mockRejectedValueOnce(new Error('event transport unavailable'));
  native.invoke.mockResolvedValue([taskFixture()]);
  const hook = renderHook(() => store.useDelegationTasks('failure-pane', 'thread-1'));
  await waitFor(() => expect(hook.result.current.subscriptionError).toBe('event transport unavailable'));
  await act(async () => { await hook.result.current.refresh(); });
  expect(hook.result.current.error).toBeNull();
  expect(hook.result.current.subscriptionHealth).toBe('failed');
  expect(hook.result.current.subscriptionError).toBe('event transport unavailable');
  let resolveSubscribe!: (unlisten: () => void) => void;
  native.listen.mockImplementationOnce(() => new Promise<() => void>(resolve => { resolveSubscribe = resolve; }));
  let retry!: Promise<void>;
  act(() => { retry = hook.result.current.retrySubscription(); });
  hook.unmount();
  const unlisten = vi.fn();
  await act(async () => { resolveSubscribe(unlisten); await retry; });
  expect(unlisten).toHaveBeenCalledTimes(1);
  expect(store.isDelegationPaneOwner('failure-pane', 'thread-1')).toBe(false);
});
