import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { useAuthStore } from "@/stores/auth-store";
import { useChatGptStore } from "@/stores/chatgpt-store";
import App from "./App";
import { getHomeDir, repairInactiveMcpConfigs } from "@/tauri/commands";
vi.mock("@/lib/addons/platform", () => ({ useAddonPlatform: vi.fn() }));
vi.mock("@/hooks/use-app-state", () => ({ useAppStateInit: vi.fn() }));
vi.mock("@/hooks/use-chatgpt-status", () => ({ useChatGptStatus: vi.fn() }));
vi.mock("@/hooks/use-keyboard-shortcuts", () => ({ useKeyboardShortcuts: vi.fn() }));
vi.mock("@/hooks/use-async-question-attention", () => ({ useAsyncQuestionAttention: vi.fn() }));
vi.mock("@/hooks/use-auth-events", () => ({ useAuthEvents: vi.fn() }));
vi.mock("@/hooks/use-tunnel-status-events", () => ({ useTunnelStatusEvents: vi.fn() }));
vi.mock("@/hooks/use-skills-sync", () => ({ useSkillsSync: vi.fn() }));
vi.mock("@/hooks/use-scrollback-serializer", () => ({ useScrollbackSerializer: vi.fn() }));
vi.mock("@/hooks/use-terminal-cache-gc", () => ({ useTerminalCacheGc: vi.fn() }));
vi.mock("@/hooks/use-terminal-theme-sync", () => ({ useTerminalThemeSync: vi.fn() }));
vi.mock("@/hooks/use-terminal-cwd-poll", () => ({ useTerminalCwdPoll: vi.fn() }));
vi.mock("@/hooks/use-automation-fire-toast", () => ({ useAutomationFireToast: vi.fn() }));
vi.mock("@/hooks/use-web-notifications", () => ({ useWebNotifications: vi.fn() }));
vi.mock("@/hooks/use-smooth-scrolling", () => ({ useSmoothScrollingInit: vi.fn() }));
vi.mock("@/hooks/use-renderer-mode", () => ({ useRendererModeInit: vi.fn() }));
vi.mock("@/hooks/use-ensure-draft-when-empty", () => ({ useEnsureDraftWhenEmpty: vi.fn() }));
vi.mock("@/hooks/use-transcript-selection-highlight", () => ({ useTranscriptSelectionHighlight: vi.fn() }));
vi.mock("@/hooks/use-active-workspace-persistence-errors", () => ({ useActiveWorkspacePersistenceErrors: vi.fn() }));
vi.mock("@/hooks/use-post-paint-session-refresh", () => ({ usePostPaintPendingSessionRefresh: vi.fn() }));
vi.mock("@/stores/feature-flags", () => ({ useFeatureFlagsInit: vi.fn() }));
vi.mock("@/components/auth/login-screen", () => ({ LoginScreen: () => <div>account login</div> }));
vi.mock("@/components/auth/chatgpt-welcome", () => ({ ChatGptWelcome: () => null }));
vi.mock("@/components/ui/sonner", () => ({ Toaster: () => null }));
vi.mock("@/components/pull-requests/pr-event-watcher", () => ({ PrEventWatcher: () => null }));
vi.mock("@/components/update/update-toast", () => ({ UpdateToast: () => null }));
vi.mock("@/components/remote/remote-connection-indicator", () => ({ RemoteConnectionBanner: () => null }));
vi.mock("@/components/layout/app-shell", () => ({ AppShell: ({ onFirstPaint }: { onFirstPaint: () => void }) => <button onClick={onFirstPaint}>local workbench</button> }));
vi.mock("@/tauri/commands", () => ({ getHomeDir: vi.fn().mockResolvedValue("/demo"), repairInactiveMcpConfigs: vi.fn().mockResolvedValue(0) }));
vi.mock("@/lib/perf/interaction-trace", () => ({ markStartup: vi.fn() }));
beforeEach(() => {
  vi.mocked(getHomeDir).mockResolvedValue("/demo");
  vi.mocked(repairInactiveMcpConfigs).mockResolvedValue(0);
  useAuthStore.setState({ user: null, isAuthenticated: false, isLoading: false, sessionStatus: "signed-out" });
  useChatGptStore.setState({ localMode: true, ready: true, cloudLogin: true });
  vi.spyOn(useAuthStore.getState(), "bootstrapSession").mockResolvedValue(undefined);
  vi.spyOn(useAuthStore.getState(), "refreshSession").mockResolvedValue(undefined);
});
afterEach(() => { cleanup(); vi.restoreAllMocks(); });
it("consumes cloud-login navigation on successful sign-in without losing local mode at sign-out", async () => {
  render(<App />);
  expect(screen.getByText("account login")).toBeTruthy();
  await act(async () => { useAuthStore.setState({ user: { id: "cloud-user", email: "builder@example.com", name: "Builder", image: null }, isAuthenticated: true, sessionStatus: "verified" }); });
  await waitFor(() => expect(useChatGptStore.getState().cloudLogin).toBe(false));
  await act(async () => { useAuthStore.setState({ user: null, isAuthenticated: false, sessionStatus: "signed-out" }); });
  expect(screen.getByText("local workbench")).toBeTruthy();
  expect(useChatGptStore.getState().localMode).toBe(true);
});
it("does not refresh a cloud session after a genuinely local shell paints", () => {
  useChatGptStore.setState({ cloudLogin: false });
  render(<App />);
  fireEvent.click(screen.getByText("local workbench"));
  expect(useAuthStore.getState().refreshSession).not.toHaveBeenCalled();
});
